### ISSUE TITLE
Building local artifacts fails due to various problems (aws-lc-sys / aws-ls-rs)

### ISSUE THREAD

**Issue by simonsan** [axodotdev/cargo-dist#1576]
I'm opening this issue here (first), as I thought, I shouldn't really edit the generated `release.yml`.

Config:

```toml

[dist.dependencies.chocolatey]
nasm = '*' # Required for building `aws-lc-sys` on Windows

[dist.dependencies.apt]
gcc-aarch64-linux-gnu = { version = '*', targets = ["aarch64-unknown-linux-gnu", "aarch64-unknown-linux-musl"] }
```

Targets:

- aarch64-unknown-linux-musl
- x86_64-unknown-linux-gnu

Affected build jobs:

- https://github.com/rustic-rs/rustic_server/actions/runs/11990078104/job/33427191835

```
--- stderr
  thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/builder/cc_builder.rs:336:9:
  COMPILER: "aarch64-linux-musl-gcc"ARGS: ["-O3", "-ffunction-sections", "-fdata-sections", "-fPIC", "-static", "-Wall", "-Wextra", "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/aws-lc/tests/compiler_features_tests/memcmp_invalid_stripped_check.c", "-Wno-unused-parameter", "-o", "/home/runner/work/rustic_server/rustic_server/target/aarch64-unknown-linux-musl/dist/build/aws-lc-sys-d43829503bcff011/out/memcmp_invalid_stripped_check"]EXECUTED: falseERROR: OUTPUT: Failed to compile memcmp_invalid_stripped_check
```

- https://github.com/rustic-rs/rustic_server/actions/runs/12032581198/job/33544768024
```
--- stderr
  thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-lc-sys-0.23.1/builder/cc_builder.rs:355:13:
  ### COMPILER BUG DETECTED ###
  Your compiler (cc) is not supported due to a memcmp related bug reported in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95189. We strongly recommend against using this compiler. 
  EXECUTED: true
  ERROR: 
  OUTPUT: 
```

- https://github.com/rustic-rs/rustic_server/actions/runs/12032581198/job/33544766295
```
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-link-lib)
```

CC:
- https://github.com/rustic-rs/rustic_server/issues/69
- https://github.com/rustic-rs/rustic_server/issues/68

**Comment by simonsan** [comment]
We fixed it by
